@extends('layouts.app')

@section('title', $product->name . ' | Management Inventory')

@section('content')
<div class="mx-auto max-w-4xl px-4 py-10 sm:px-6 lg:px-8">
    <a href="{{ route('products.index') }}" class="text-sm font-bold text-slate-500 hover:text-slate-900">← Back to products</a>
    <div class="mt-6 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p class="text-sm font-semibold uppercase tracking-[0.2em] text-green-600">Product details</p><h1 class="mt-2 text-3xl font-extrabold tracking-tight text-slate-900">{{ $product->name }}</h1><p class="mt-2 text-sm text-slate-500">SKU {{ $product->sku }} · {{ $product->category }}</p></div><a href="{{ route('products.edit', $product) }}" class="inline-flex justify-center rounded-lg bg-green-600 px-4 py-2.5 text-sm font-bold text-white hover:bg-green-700">Edit product</a></div>
    <div class="mt-8 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="grid gap-6 border-b border-slate-200 p-6 sm:grid-cols-3"><div><p class="text-xs font-bold uppercase tracking-wider text-slate-400">Quantity</p><p class="mt-2 text-2xl font-extrabold text-slate-900">{{ $product->quantity }}</p></div><div><p class="text-xs font-bold uppercase tracking-wider text-slate-400">Reorder level</p><p class="mt-2 text-2xl font-extrabold text-slate-900">{{ $product->reorder_level }}</p></div><div><p class="text-xs font-bold uppercase tracking-wider text-slate-400">Unit price</p><p class="mt-2 text-2xl font-extrabold text-green-600">{{ number_format($product->unit_price, 2) }}</p></div></div><dl class="grid gap-x-8 gap-y-6 p-6 sm:grid-cols-2"><div><dt class="text-xs font-bold uppercase tracking-wider text-slate-400">Supplier</dt><dd class="mt-2 text-sm font-semibold text-slate-700">{{ $product->supplier ?: 'Not provided' }}</dd></div><div><dt class="text-xs font-bold uppercase tracking-wider text-slate-400">Status</dt><dd class="mt-2">@if($product->isOutOfStock())<span class="rounded-full bg-red-50 px-2.5 py-1 text-xs font-bold text-red-700">Out of stock</span>@elseif($product->isLowStock())<span class="rounded-full bg-amber-50 px-2.5 py-1 text-xs font-bold text-amber-700">Low stock</span>@else<span class="rounded-full bg-green-50 px-2.5 py-1 text-xs font-bold text-green-700">In stock</span>@endif</dd></div><div class="sm:col-span-2"><dt class="text-xs font-bold uppercase tracking-wider text-slate-400">Description</dt><dd class="mt-2 text-sm leading-6 text-slate-600">{{ $product->description ?: 'No description provided.' }}</dd></div></dl></div>
</div>
@endsection
